
export const BASE_URL = 'http://localhost:3000';

export enum EVENT {
  LOAD_APP = 'onAppLoad',
  SHOW_ALERT = 'onShowAlert',
  ROUTER_CHANGE_PAGE = 'onChangePage',
  CARS_AFTER_RENDER = 'onRenderCars',
  TRY_CREATE_CAR = 'onCreateCar',
  TRY_UPDATE_CAR = 'onUpdateCar',
  SELECT_CAR = 'onSelectCar',
  TRY_REMOVE_CAR = 'onTryRemoveCar',
  REMOVE_CAR = 'onRemoveCar',
  START_CAR_ENGINE = 'onStartCarEngine',
  ACCELERATE_CAR = 'onAccelerateCar',
  BREAK_CAR = 'onBreakCar',
  START_RACE = 'onStartRace',
  RESET_CARS = 'onResetCars',
  WINNER_FINISH = 'onWinnerFinish',
  RACE_END = 'onRaceEnd',
  GARAGE_CHANGE_PAGE = 'onGarageChangePage',
  WINNERS_CHANGE_PAGE = 'onWinnersChangePage',
  GENERATE_CARS = 'onGenerateCars',
  LOAD_WINNERS = 'onLoadWinners',
  GET_WINNERS = 'onGetWinners',
}

export const MIN_CAR_NAME_LENGTH = 3;

export enum ITEMS_PER_PAGE {
  GARAGE = 7,
  WINNERS = 7,
}

export const GENERATED_CARS_NUMBER = 100;
export const carModels = [
  'Abarth',
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Dacia',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar ',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Mazda ',
  'Mercedes-Benz',
  'Mercury',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Pontiac',
  'Porsche',
  'Ram',
  'Renault',
  'Saab',
  'Saturn',
  'Scion',
  'Seat',
  'Skoda',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Wiesmann',
]